from .model import Generator_resnet, Generator_resnet_mtk, Discriminator, GeneratorUnetSeg, GeneratorUnetImg, GeneratorUnetSegImg,UNet_deep,GeneratorUnetSegImgGAN,DiscriminatorImg,DiscriminatorSeg,GeneratorSRGANSegImg,Discriminator,usuperes,\
GeneratorSRGANSeg,GeneratorSRGANImg,DiscriminatorOriginal,GeneratorSRGANSegImgDouble
